{{- $svc := index .Values "gateway" }}
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "modu-erp.labels" . | nindent 4 }}
    app.kubernetes.io/name: gateway
spec:
  type: {{ $svc.service.type }}
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - port: {{ $svc.service.port }}
      targetPort: {{ $svc.service.port }}
      protocol: TCP
